### PR TITLE
Draft: Feature/extract data from api

### PR DESCRIPTION
**Pull request by MREugeneJ7**
Adds a functionality to extract the latest validated data from the API for all the stations

### CODE REVIEW

**Comment by MREugeneJ7** [comment]
Missing exporting a function, refactoring, and trying to make the functionality faster by making it as asynchronous as possible

Maybe creating a second function to update a single station, and only using the current one for the initial load.

**Comment by alu0101056944** [comment]
Looks good, although I don't understand why the `flat(Infinity)` is at:

```js
async function addReadingsToSensors(station, readings) {
    station.sensors.forEach(element => {
        let medida = readings
            .filter(sR => sR.id_weatherstationsensor == element.id)
            .map(sR => sR.dates)
            .flat(Infinity)
            .filter(sR => sR.is_validated)
            .pop()
        if (medida) {
            element.medida = medida.values[0]
        }
    });
}
```

Each element in the date array is an object and flat affects arrays only, right? So I am guessing it's for preventing in case there are nested arrays.

**Review by alu0101056944 — APPROVED** [review]

**Comment by MREugeneJ7** [comment]
> Looks good, although I don't understand why the `flat(Infinity)` is at:
> 
> ```js
> async function addReadingsToSensors(station, readings) {
>     station.sensors.forEach(element => {
>         let medida = readings
>             .filter(sR => sR.id_weatherstationsensor == element.id)
>             .map(sR => sR.dates)
>             .flat(Infinity)
>             .filter(sR => sR.is_validated)
>             .pop()
>         if (medida) {
>             element.medida = medida.values[0]
>         }
>     });
> }
> ```
> 
> Each element in the date array is an object and flat affects arrays only, right? So I am guessing it's for preventing in case there are nested arrays.

The thing is inside dates there's an array containing a single object, so I wanted to get rid of the array. Which is doing nothing.

**Review by elenamsd — APPROVED** [review]
well done!😉

**Pull request merged**
